name: VM3 QPrefix Runtime

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  qprefix:
    name: vm3-qprefix-runtime-check
    runs-on: ubuntu-latest
    steps:
      - run: echo VM3_QPREFIX_RUNTIME_CHECK_QH9F17
